apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hdfs-zk-0
spec:
  storageClassName: zk-manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sda/hdfs-zk"
  nodeAffinity: # nodeAffinity is required when using local volumes.
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - exxact4544532476

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hdfs-zk-1
spec:
  storageClassName: zk-manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sda/hdfs-zk"
  nodeAffinity: # nodeAffinity is required when using local volumes.
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - A161100900

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hdfs-zk-2
spec:
  storageClassName: zk-manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sda/hdfs-zk"
  nodeAffinity: # nodeAffinity is required when using local volumes.
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - A161100899