apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hdfs-data0
  labels:
    node: '55'
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda/hdfs-data0"
  nodeAffinity: # nodeAffinity is required when using local volumes.
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - exxact4544531989
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hdfs-data1
  labels:
    node: '56'
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda/hdfs-data1"
  nodeAffinity: # nodeAffinity is required when using local volumes.
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - exxact4544532476