apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hdfs-namenode-0
  labels:
    node: '56'
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda/hdfs-namenode"
  nodeAffinity: # nodeAffinity is required when using local volumes.
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - exxact4544532476

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hdfs-namenode-1
  labels:
    node: '57'
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda/hdfs-namenode"
  nodeAffinity: # nodeAffinity is required when using local volumes.
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - A161100900